spring.application.name=trimzo
# ===========================
# SERVER
# ===========================
server.port=8080

# ===========================
# DATABASE
# ===========================
spring.datasource.url=jdbc:postgresql://localhost:5432/trimzo_db
spring.datasource.username=trimzo_user
spring.datasource.password=trimzo_password_123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================
# JPA / HIBERNATE
# ===========================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===========================
# FLYWAY
# ===========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===========================
# JWT
# ===========================
jwt.secret=trimzoSecretKeyForJWTTokenGenerationMinimum32Chars
jwt.expiration=86400000

# ===========================
# APP
# ===========================
app.base-url=http://localhost:8080

# ===========================
# ASYNC
# ===========================
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10